Option Explicit

Sub AskExcelAIAssistant()
    ' === VARIABLES ===
    Dim http As Object, regex As Object, matches As Object
    Dim jsonRequest As String, jsonResponse As String
    Dim userPrompt As String, apiKey As String, aiText As String
    Dim wsData As Worksheet, wsDashChart As Worksheet
    Dim rowData As String, fullPrompt As String
    Dim rr As Long, cc As Long, totalRows As Long, lastCol As Long
    Dim cht As ChartObject
    Dim chartType As String, columnsList As String
    Dim plotCols() As String
    Dim xValues() As Double, yValues() As Double
    Dim xCol As Long, yCol As Long, i As Long
    Dim plotPos As Long, plotLine As String, parts() As String
    
    ' === CONFIG ===
    apiKey = ""
    Set wsData = ThisWorkbook.Sheets("customers (3)")
    Set wsDashChart = ThisWorkbook.Sheets("DASHBOARD (2)")
    
    ' === USER INPUT ===
    userPrompt = InputBox("Ask me anything about your customer dataset:", "Excel AI Assistant")
    If Trim(userPrompt) = "" Then Exit Sub
    
    ' === EXTRACT FOR ALL ROWS(501) ===
    totalRows = WorksheetFunction.Min(501, wsData.UsedRange.Rows.Count)
    lastCol = wsData.UsedRange.Columns.Count
    rowData = ""
    
    For rr = 1 To totalRows
        For cc = 1 To lastCol
            rowData = rowData & CleanForJSON(CStr(wsData.Cells(rr, cc).value)) & " | "
        Next cc
        rowData = rowData & " || "
    Next rr
    
    ' === BUILD PROMPT ===
    fullPrompt = "You are an expert Excel data analyst. " & _
                 "Use ONLY the dataset below to answer factually. " & _
                 "Always explain your reasoning in detail before giving the final answer. " & _
                 "If the user asks about a plot, chart, or graph, you MUST provide a parseable plot suggestion in this format: " & _
                 "PLOT: chartType | columns: Col1,Col2. Do not output charts in any other format." & _
                 " QUESTION: " & CleanForJSON(userPrompt) & _
                 " DATA: " & rowData
    
    ' === JSON PAYLOAD ===
    jsonRequest = "{""model"":""llama-3.3-70b-versatile"",""messages"":[{""role"":""user"",""content"":""" & _
                  fullPrompt & """}],""temperature"":0.2}"
    
    ' === SEND REQUEST ===
    On Error GoTo HttpError
    Set http = CreateObject("MSXML2.XMLHTTP")
    http.Open "POST", "https://api.groq.com/openai/v1/chat/completions", False
    http.setRequestHeader "Content-Type", "application/json"
    http.setRequestHeader "Authorization", "Bearer " & apiKey
    http.Send jsonRequest
    jsonResponse = http.responseText
    On Error GoTo 0
    
    ' === PARSE AI RESPONSE ===
    Set regex = CreateObject("VBScript.RegExp")
    regex.Global = False
    regex.IgnoreCase = True
    regex.pattern = """content"":\s*""([^""]+)"""
    Set matches = regex.Execute(jsonResponse)
    
    If matches.Count > 0 Then
        aiText = Replace(matches(0).SubMatches(0), "\n", vbCrLf)
        aiText = Replace(aiText, "\\", "\")
    Else
        aiText = "? No readable AI response. Raw JSON: " & Left(jsonResponse, 400)
    End If
    
    ' === DISPLAY AI RESPONSE ON DASHBOARD (2) in A52 ===
    wsDashChart.Range("A52").value = aiText
    wsDashChart.Columns("A:A").AutoFit
    
    ' === PARSE AI-SUGGESTED PLOT ===
    chartType = ""
    columnsList = ""
    plotPos = InStr(1, aiText, "PLOT:", vbTextCompare)
    
    If plotPos > 0 Then
        plotLine = Mid(aiText, plotPos)
        parts = Split(plotLine, "|")
        If UBound(parts) >= 1 Then
            chartType = Trim(Replace(parts(0), "PLOT:", "", , , vbTextCompare))
            columnsList = Trim(Replace(parts(1), "columns:", "", , , vbTextCompare))
        End If
    End If
    
    ' === CREATE SCATTER PLOT ONLY IF REQUESTED ===
    If chartType <> "" And columnsList <> "" Then
        plotCols = Split(columnsList, ",")
        
        ' Only delete charts generated by AI (tagged name)
        For Each cht In wsDashChart.ChartObjects
            If Left(cht.Name, 7) = "AIPlot_" Then cht.Delete
        Next cht
        
        If LCase(chartType) = "scatter" Or LCase(chartType) = "scatter plot" Then
            If UBound(plotCols) <> 1 Then
                MsgBox "Scatter plot requires exactly two columns.", vbExclamation
                Exit Sub
            End If
            
            ' Find column indexes
            xCol = 0
            yCol = 0
            For cc = 1 To lastCol
                If LCase(Trim(wsData.Cells(1, cc).value)) = LCase(Trim(plotCols(0))) Then xCol = cc
                If LCase(Trim(wsData.Cells(1, cc).value)) = LCase(Trim(plotCols(1))) Then yCol = cc
            Next cc
            
            If xCol = 0 Or yCol = 0 Then
                MsgBox "AI-suggested columns not found in the dataset.", vbExclamation
                Exit Sub
            End If
            
            ' Fill arrays with values
            ReDim xValues(1 To totalRows)
            ReDim yValues(1 To totalRows)
            For i = 2 To totalRows + 1
                If IsNumeric(wsData.Cells(i, xCol).value) And IsNumeric(wsData.Cells(i, yCol).value) Then
                    xValues(i - 1) = CDbl(wsData.Cells(i, xCol).value)
                    yValues(i - 1) = CDbl(wsData.Cells(i, yCol).value)
                End If
            Next i
            
            ' Create scatter chart
            Set cht = wsDashChart.ChartObjects.Add(Left:=300, Top:=50, Width:=500, Height:=300)
            cht.Name = "AIPlot_Scatter"
            With cht.Chart
                .chartType = xlXYScatter
                .SeriesCollection.NewSeries
                .SeriesCollection(1).xValues = xValues
                .SeriesCollection(1).Values = yValues
                .SeriesCollection(1).Name = "Legend"
                .HasTitle = True
                .ChartTitle.Text = "Scatter Plot: " & plotCols(0) & " vs " & plotCols(1)
                .Axes(xlCategory).HasTitle = True
                .Axes(xlCategory).AxisTitle.Text = plotCols(0)
                .Axes(xlValue).HasTitle = True
                .Axes(xlValue).AxisTitle.Text = plotCols(1)
            End With
            
            MsgBox "? Scatter plot created successfully on '" & wsDashChart.Name & "'!", vbInformation
        End If
    End If
    
    Exit Sub

HttpError:
    MsgBox "HTTP request failed: " & Err.Description, vbCritical
End Sub

' === CLEAN TEXT FOR JSON ===
Private Function CleanForJSON(ByVal txt As String) As String
    txt = Replace(txt, "\", "\\")
    txt = Replace(txt, """", "'")
    txt = Replace(txt, vbCr, " ")
    txt = Replace(txt, vbLf, " ")
    txt = Replace(txt, vbTab, " ")
    txt = Replace(txt, "/", " ")
    txt = Replace(txt, vbFormFeed, " ")
    txt = Replace(txt, vbVerticalTab, " ")
    CleanForJSON = Trim(txt)
End Function
